FROM acr.aishu.cn/public/nginx:1.22.1-alpine-latest
ENV  HOST_IP=127.0.0.1

COPY default.conf.template /etc/nginx/conf.d
COPY docker-entrypoint.sh /docker-entrypoint.d/workflow-docker-entrypoint.sh
RUN envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf

COPY ./dist /usr/share/nginx/html/doc-audit-client
EXPOSE 1005
CMD ["nginx", "-g", "daemon off;"]