parameters:
  - name: utilRepo
    default: ''
  - name: publicRepo
    default: ''
  - name: uiRepo
    default: ''
  - name: sweetuiRepo
    default: ''
  - name: jobName
    default: ''

jobs:
  - job: ${{ parameters.jobName }}
    displayName: '静态检查和单元测试'
    pool: 
      name: ASConsole
    workspace:
      clean: all
    steps:
      - checkout: self
        fetchDepth: 1

      - script: |
          rm -rf ./**
        displayName: 'remove source'
        condition: always()