parameters:
  - name: pool
    default:
  - name: compileContainer
    default:
  - name: utArtifactName
    default:
  - name: utReportName
    default:
  - name: lintReportName
    default:
  - name: coverageReportName
    default:

jobs:
  - job: Code_Check
    displayName: Code Check
    container: ${{ parameters.compileContainer }}
    pool:
      name: ${{ parameters.pool }}
    workspace:
      clean: all
    steps:
      - checkout: self
      - script: |
          set -ex
          mvn clean org.apache.maven.plugins:maven-pmd-plugin:3.19.0:pmd install -Dmaven.test.skip=true
          rm -rf coverage_report
          mkdir -p coverage_report/dc-main
          mkdir -p coverage_report/reports

          cp dc-main/target/pmd.xml coverage_report/dc-main/${{ parameters.lintReportName }}
        continueOnError: false
        displayName: Check Code
      # 执行UT
      - script: |
          set -ex
          mvn clean test
          jrm coverage_report/${{ parameters.utReportName }} ./**/target/surefire-reports/*.xml
          cp -rpf dc-main/target/jacoco-report coverage_report/reports

        displayName: 生成单元测试结果及覆盖率报告
      - task: CopyFiles@2
        inputs:
          SourceFolder: $(Build.SourcesDirectory)
          contents: |
            coverage_report/**
          targetFolder: $(Build.BinariesDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.BinariesDirectory)
          artifactName: ${{ parameters.utArtifactName }}

  - job: Lint_Check
    displayName: Lint Reports and Quality Gates
    container: dotnet
    dependsOn: Code_Check
    pool:
      name: ${{ parameters.pool }}
    workspace:
      clean: all
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: ${{ parameters.utArtifactName }}
          downloadPath: $(Build.BinariesDirectory)

      - task: PublishTestResults@2
        displayName: Publish Lint Report
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: '$(Build.BinariesDirectory)/${{ parameters.utArtifactName }}/coverage_report/**/${{ parameters.lintReportName }}'
          testRunTitle: Lint
          failTaskOnFailedTests: false

      - task: BuildQualityChecks@8
        displayName: Quality Gate Lint
        inputs:
          checkWarnings: true
          warningFailOption: 'fixed'
          warningThreshold: '0'
          showStatistics: false
          evaluateTaskWarnings: false
          evaluateFileWarnings: true
          warningFilesFolder: '$(Build.BinariesDirectory)'
          warningFiles: '${{ parameters.utArtifactName }}/coverage_report/**/${{ parameters.lintReportName }}'
          warningFileFilters: '/^<\/violation>.*?$/'
          warningFilesArtifact: '${{ parameters.utArtifactName }}'

  - job: UT_Check
    displayName: UT Reports and Quality Gates
    container: dotnet
    dependsOn: Code_Check
    pool:
      name: ${{ parameters.pool }}
    workspace:
      clean: all
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: ${{ parameters.utArtifactName }}
          downloadPath: $(Build.BinariesDirectory)

      - task: PublishTestResults@2
        displayName: Publish UT Report
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: '$(Build.BinariesDirectory)/${{ parameters.utArtifactName }}/coverage_report/${{ parameters.utReportName }}'
          testRunTitle: UT
          failTaskOnFailedTests: false

      - task: BuildQualityChecks@8
        displayName: Quality Gate UT
        inputs:
          checkWarnings: true
          warningFailOption: 'fixed'
          warningThreshold: '0'
          showStatistics: false
          evaluateTaskWarnings: false
          evaluateFileWarnings: true
          warningFilesFolder: '$(Build.BinariesDirectory)'
          warningFiles: '${{ parameters.utArtifactName }}/coverage_report/${{ parameters.utReportName }}'
          warningFileFilters: '/^<\/error>.*?$/'
          warningFilesArtifact: '${{ parameters.utArtifactName }}'

  - job: Coverage_Check
    displayName: Coverage Reports and Quality Gates
    container: dotnet
    dependsOn: Code_Check
    pool:
      name: ${{ parameters.pool }}
    workspace:
      clean: all
    steps:
      - checkout: self
        fetchDepth: 1
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: ${{ parameters.utArtifactName }}
          downloadPath: $(Build.SourcesDirectory)

      - task: PublishBuildArtifacts@1
        displayName: Publish Summary Reports To Artifacts
        condition: succeeded()
        inputs:
          PathToPublish: '$(Build.SourcesDirectory)/${{parameters.utArtifactName}}/coverage_report/reports/jacoco-report'
          ArtifactsName: coveragereports

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'JaCoCo'
          summaryFileLocation: '$(Build.SourcesDirectory)/${{parameters.utArtifactName}}/coverage_report/reports/jacoco-report/jacoco.xml'
          reportDirectory: '$(Build.SourcesDirectory)/${{parameters.utArtifactName}}/coverage_report/reports/jacoco-report'
          failIfCoverageEmpty: false

      - task: BuildQualityChecks@8
        displayName: Quality Gate Coverage
        inputs:
          coverageType: 'lines'
          coverageFailOption: 'fixed'
          checkCoverage: true
          coverageThreshold: '50.0'
